version: '3.8'

services:
  frontend:
    # image: jhonathass/talkhub-frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    # image: jhonathass/talkhub-backend
    build:
      context: ./backend
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: